/*
 * generated by Xtext 2.40.0
 */
package org.example.pipelinedsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PipelineDSLRuntimeModule extends AbstractPipelineDSLRuntimeModule {
}
