/*
 * generated by Xtext 2.40.0
 */
package org.example.pipelinedsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PipelineDSLStandaloneSetup extends PipelineDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new PipelineDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
