/*
 * generated by Xtext 2.40.0
 */
package org.example.pipelinedsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PipelineDSLUiModule extends AbstractPipelineDSLUiModule {

	public PipelineDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
