/*
 * generated by Xtext 2.40.0
 */
package org.example.pipelinedsl.ide;


/**
 * Use this class to register ide components.
 */
public class PipelineDSLIdeModule extends AbstractPipelineDSLIdeModule {
}
