/*
 * generated by Xtext 2.40.0
 */
package org.example.pipelinedsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.pipelinedsl.PipelineDSLRuntimeModule;
import org.example.pipelinedsl.PipelineDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PipelineDSLIdeSetup extends PipelineDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PipelineDSLRuntimeModule(), new PipelineDSLIdeModule()));
	}
	
}
